marvels/urls.py
from django.contrib import admin
from django.urls import path,include
import spiderman
urlpatterns = [
    path('admin/', admin.site.urls),
    path('spiderman/',include('spiderman.urls')),
]

spiderman/urls.py
from django.urls import path
from spiderman.views import *
app_name='spiderman'
urlpatterns=[
    path('aditya/',aditya,name='aditya'),
    path('neel/',neel,name='neel'),
]

spiderman/models.py
from django.db import models

# Create your models here.

spiderman/views.py
from django.shortcuts import render
def aditya(request):
    return render(request,'aditya.html',context={'name':'aditya'})

def neel(request):
    return render(request,'neel.html',context={'greetings':'Thanks for reading'})

templates/aditya.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>About</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    {% if name == 'aditya' %}
    
    
    <center><div class="card" style="width: 20rem;">
        <img src="{% static 'images/adi.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">About me</h5>
          <p>Hii i am Aditya</p>
          <p class="card-text">I am from odisha but currently staying at Bengaluru, Marathahalli</p>
          <p>Hobbies</p>
          <p>{{name}} loves to sing and writes lots of poems and affirmations</p>
    <a href="{% url 'spiderman:neel' %}" class="btn btn-primary"> previous</a>  
        </div>
      </div></center>
    {% endif %}
<footer>
    <center><p>Happy learning 😁</p></center>
</footer>

  </body>
</html>

templates/neel.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Notes</title>
    <link rel="stylesheet" href="{% static 'css/c2.css' %}">
  </head>
  <body>
    <nav id="navbar-example2" class="navbar navbar-light bg-light px-3">
        <a class="navbar-brand" href="#">Django knowledge</a>
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link" href="#scrollspyHeading1">About this project</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#scrollspyHeading2">This project consist of?</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#scrollspyHeading3">This project is All about?</a></li>
              <li><a class="dropdown-item" href="#scrollspyHeading4">Benifits to whom?</a></li>
              <li><hr class="dropdown-divider"></li>
            </ul>
          </li>
        </ul>
      </nav>
      <article><div data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-offset="0" class="scrollspy-example" tabindex="0">
        <h4 id="scrollspyHeading1">Introduction</h4>
        <p><ol>This is my new web page where i have done some bootstrap work and several things like specific url mapping, specific url navigation, specific static files.</ol></p>
        <h4 id="scrollspyHeading2">Things needed</h4>
        <p><ul>HTML</ul>
        <ul>CSS</ul>
    <ul>Bootstrap</ul>
<ul>Python</ul>
<ul>Django</ul></p>
        <h4 id="scrollspyHeading3">Benifits</h4>
        <ol><p>That how it will be benificial to the Python Full stack web developer who wants to learn web apps,
        </p>
        <p>  Because of Bootstrap we can easily built our frontend page quickly.</p></ol>
        <h4 id="scrollspyHeading4"></h4>

      </div>
    </article>
      

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    {% if greetings == 'Thanks for reading' %}
    
    <p>{{greetings}}</p>
    
      <a href="{% url 'spiderman:aditya' %}" class="btn btn-primary">Next</a>
    {% endif %}
  </body>
</html>